# Generated by Django 3.0.8 on 2020-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200819_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='complianceCheck',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
