# Generated by Django 3.0.8 on 2020-09-23 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200923_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=datetime.date(2020, 9, 23), max_length=50, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
