# Generated by Django 3.0.8 on 2020-09-23 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200923_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default=datetime.date(2020, 9, 23), max_length=50),
        ),
    ]
