# Generated by Django 3.0.8 on 2020-09-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200923_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.CharField(default='14:7:12', max_length=50),
        ),
    ]
