# Generated by Django 3.0.8 on 2020-09-24 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_messages_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2020, 9, 24), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2020, 9, 24), max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default=datetime.date(2020, 9, 24), max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.CharField(default='12:33:6', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 9, 24), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 9, 24), max_length=50, null=True),
        ),
    ]
