# Generated by Django 3.0.8 on 2020-10-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201011_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.CharField(default='16:50:26', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='logIn_time',
            field=models.TimeField(null=True, verbose_name='LOG IN'),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='week_number',
            field=models.IntegerField(default=1, null=True, verbose_name='WEEKNUMBER'),
        ),
    ]
