# Generated by Django 3.0.8 on 2020-10-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201013_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclescheduleddate',
            name='week_number',
            field=models.IntegerField(default=1, null=True, verbose_name='WEEKNUMBER'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.CharField(default='13:7:10', max_length=50),
        ),
    ]
