# Generated by Django 3.0.8 on 2020-10-26 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201013_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2020, 10, 26), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2020, 10, 26), max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default=datetime.date(2020, 10, 26), max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.CharField(default='20:5:20', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 10, 26), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 10, 26), max_length=50, null=True),
        ),
    ]
