# Generated by Django 3.0.8 on 2020-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201101_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.CharField(default='16:48:42', max_length=50),
        ),
    ]
