# Generated by Django 3.0.8 on 2020-11-07 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201101_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclescheduleddate',
            name='location',
            field=models.CharField(default='DBS2', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2020, 11, 7), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2020, 11, 7), max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default=datetime.date(2020, 11, 7), max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.CharField(default='17:48:27', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 11, 7), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 11, 7), max_length=50, null=True),
        ),
    ]
