# Generated by Django 3.0.8 on 2020-12-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20201211_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('current_index', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
