# Generated by Django 3.0.8 on 2020-12-11 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20201211_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyServiceLockTwo',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dailyservicelock',
            name='service_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
