# Generated by Django 3.0.8 on 2020-12-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20201218_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverhistory',
            name='van_id',
        ),
        migrations.AddField(
            model_name='driverhistory',
            name='registration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
