# Generated by Django 3.0.8 on 2020-12-23 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20201223_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyServiceOverrideTwo',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
