# Generated by Django 3.0.8 on 2020-12-29 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20201227_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationsheet',
            name='DpmoBonus',
            field=models.IntegerField(default=1, null=True, verbose_name='miles'),
        ),
        migrations.AddField(
            model_name='validationsheet',
            name='Missortfourth',
            field=models.IntegerField(default=1, null=True, verbose_name='miles'),
        ),
        migrations.AddField(
            model_name='validationsheet',
            name='Missortsixth',
            field=models.IntegerField(default=1, null=True, verbose_name='miles'),
        ),
        migrations.AddField(
            model_name='validationsheet',
            name='R2',
            field=models.IntegerField(default=1, null=True, verbose_name='miles'),
        ),
        migrations.AddField(
            model_name='validationsheet',
            name='R4',
            field=models.IntegerField(default=1, null=True, verbose_name='miles'),
        ),
        migrations.AddField(
            model_name='validationsheet',
            name='R6',
            field=models.IntegerField(default=1, null=True, verbose_name='miles'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2020, 12, 29), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2020, 12, 29), max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 12, 29), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2020, 12, 29), max_length=50, null=True),
        ),
    ]
