# Generated by Django 3.0.8 on 2020-12-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20201229_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationsheet',
            name='station',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
