# Generated by Django 3.0.8 on 2021-01-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20210128_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverhistory',
            name='endDate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
