# Generated by Django 3.0.8 on 2021-02-01 17:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20210201_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='registration',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None),
        ),
    ]
