# Generated by Django 3.0.8 on 2021-02-01 18:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20210201_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='compliance_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
