# Generated by Django 3.0.8 on 2021-02-01 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210201_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None),
        ),
    ]
