# Generated by Django 3.0.8 on 2021-02-11 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20210201_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2021, 2, 11), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2021, 2, 11), max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2021, 2, 11), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='logIn_time',
            field=models.TimeField(default='00:00', null=True, verbose_name='LOG IN'),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='logOut_time',
            field=models.TimeField(default='00:00', null=True, verbose_name='LOG OUT'),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2021, 2, 11), max_length=50, null=True),
        ),
    ]
