# Generated by Django 3.0.8 on 2021-02-24 13:21

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20210211_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerClass',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30, null=True)),
                ('manager_id', models.CharField(max_length=100, null=True)),
                ('logOut_time', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('logIn_time', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('pages_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('submitted_data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='scheduleddate',
            name='manager_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='validationsheet',
            name='manager_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclescheduleddate',
            name='manager_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2021, 2, 24), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2021, 2, 24), max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2021, 2, 24), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2021, 2, 24), max_length=50, null=True),
        ),
    ]
