# Generated by Django 3.0.8 on 2021-03-01 14:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210224_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLock',
            fields=[
                ('validation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30, null=True)),
                ('overriden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2021, 3, 1), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2021, 3, 1), max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2021, 3, 1), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2021, 3, 1), max_length=50, null=True),
        ),
    ]
