# Generated by Django 3.0.8 on 2021-03-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20210302_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='offboarded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
