# Generated by Django 3.0.8 on 2021-03-11 16:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20210311_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddate',
            name='manager_movement',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None),
        ),
    ]
