# Generated by Django 3.0.8 on 2021-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20210311_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymessage',
            name='dateSubmit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
