# Generated by Django 3.0.8 on 2021-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20210325_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthourlist',
            name='lockid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eighthourlist',
            name='locktype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
