# Generated by Django 3.0.8 on 2021-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20210325_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthourlist',
            name='current_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
