# Generated by Django 3.0.8 on 2021-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_eighthourlist_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerchangelist',
            name='driver_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
