# Generated by Django 3.0.8 on 2021-05-11 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20210510_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2021, 5, 11), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='creationDate',
            field=models.CharField(default=datetime.date(2021, 5, 11), max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2021, 5, 11), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclescheduleddate',
            name='date',
            field=models.CharField(default=datetime.date(2021, 5, 11), max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ComplianceVan',
            fields=[
                ('Compliance_Van_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Assighned_Date', models.CharField(max_length=30, null=True)),
                ('Returned_Date', models.CharField(max_length=30, null=True)),
                ('Driver_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Driver')),
                ('vehicle_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Vehicles')),
            ],
        ),
    ]
