# Generated by Django 3.0.8 on 2021-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_compliancevan_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Compliance_Van',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
