# Generated by Django 3.0.8 on 2021-05-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_driver_compliance_van'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancevan',
            name='vehicle_Id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
