# Generated by Django 3.0.8 on 2021-06-14 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20210614_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='startList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, size=None),
        ),
    ]
